name: Create matrix run

on:
  workflow_dispatch:

env: 
  GHA_SUMMARY

jobs:
  run-python-files:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        py-files:
          - a
          - b
          - c
  
    steps:
  
      - name: checkout repo
        uses: actions/checkout@v3
  
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
  
      - name: Run Python Files
        run: |
          python ./matrix_pages/${{ matrix.py-files }}.py
          cat github_output.txt >> $GHA_SUMMARY
  get-env-var:
    steps:
      - name: env var to summary
        run: | 
          echo $GHA_SUMMARY >> $GITHUB_STEP_SUMMARY

  

