name: Create matrix run

defaults:
  run:
    shell: bash -leo pipefail {0}

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
  strategy:
    matrix:
      py-files:
        - a
        - b
        - c

  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 #install the python needed

    - name: Run Python Files
      run: |
        python ./matrix_pages/{matrix.py-files}.py
